import { LlmProvider } from './provider.js';

// Local provider — no external network calls. Returns deterministic, pattern-matched
// JSON/text suitable for the FetchLab AI endpoints when an enterprise wants to run
// with zero AI calls. The output is intentionally simple — useful as a fallback,
// not a replacement for a real LLM.
export class LocalProvider extends LlmProvider {
  get name() { return 'local'; }

  async chat(messages, options = {}) {
    const { system, messages: rest } = LlmProvider.splitSystem(messages);
    const sys = (options.system || system || '').toLowerCase();
    const user = rest.map(m => m.content).join('\n');
    const lower = user.toLowerCase();

    let content;
    if (sys.includes('http request generator') || sys.includes('generate-request')) {
      content = JSON.stringify(this._generateRequest(user));
    } else if (sys.includes('test assertions') || sys.includes('fl.test')) {
      content = this._generateTests(user);
    } else if (sys.includes('debugging assistant') || sys.includes('diagnose')) {
      content = JSON.stringify(this._diagnose(user));
    } else if (sys.includes('response diff') || sys.includes('explain')) {
      content = JSON.stringify(this._explainDiff(user));
    } else if (sys.includes('openapi')) {
      content = this._generateSpec(user);
    } else if (lower.includes('ping') || lower.includes('test connection')) {
      content = 'pong (local provider, no LLM call)';
    } else {
      content = 'Local heuristic provider is active. No external LLM calls are being made. Configure an external provider for richer responses.';
    }

    return {
      content,
      usage: { input_tokens: 0, output_tokens: 0, model: 'local-heuristic', provider: 'local' },
    };
  }

  _generateRequest(prompt) {
    const urlMatch = prompt.match(/https?:\/\/\S+/);
    const url = urlMatch ? urlMatch[0].replace(/[.,;]$/, '') : 'https://api.example.com/resource';
    const methodMatch = prompt.match(/\b(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\b/i);
    const method = (methodMatch ? methodMatch[1] : 'GET').toUpperCase();
    const wantsJson = /json|body|payload|post/i.test(prompt);
    return {
      method,
      url,
      headers: wantsJson ? [{ key: 'Content-Type', value: 'application/json' }] : [],
      params: [],
      body: wantsJson ? { type: 'json', content: '{}' } : { type: 'none', content: '' },
      name: prompt.slice(0, 50) || `${method} request`,
    };
  }

  _generateTests() {
    return [
      'fl.test("status is 2xx", () => {',
      '  fl.expect(fl.response.status).toBeGreaterThan(199);',
      '  fl.expect(fl.response.status).toBeLessThan(300);',
      '});',
      'fl.test("response time reasonable", () => {',
      '  fl.expect(fl.response.time).toBeLessThan(5000);',
      '});',
    ].join('\n');
  }

  _diagnose(prompt) {
    const statusMatch = prompt.match(/"status"\s*:\s*(\d+)/);
    const status = statusMatch ? Number(statusMatch[1]) : 0;
    let summary, likelyCause, fixes;
    if (status === 401 || status === 403) {
      summary = 'Authentication or authorization rejected the request.';
      likelyCause = 'Missing, expired, or insufficient credentials.';
      fixes = [
        { title: 'Check the Authorization header', detail: 'Verify the token is present and not expired.' },
        { title: 'Confirm scope/role', detail: 'The token may lack permission for this endpoint.' },
      ];
    } else if (status === 404) {
      summary = 'The resource path was not found.';
      likelyCause = 'Wrong URL path or missing resource ID.';
      fixes = [{ title: 'Verify URL', detail: 'Double-check the path and any IDs.' }];
    } else if (status >= 500) {
      summary = 'Server-side error.';
      likelyCause = 'Upstream service failure or bad request shape.';
      fixes = [{ title: 'Retry with backoff', detail: 'Transient errors often resolve on retry.' }];
    } else {
      summary = 'The request failed.';
      likelyCause = 'See the response body for details.';
      fixes = [{ title: 'Inspect response body', detail: 'The API likely returned an error message.' }];
    }
    return {
      summary,
      severity: status >= 500 ? 'critical' : 'warning',
      likelyCause,
      fixes,
    };
  }

  _explainDiff() {
    return {
      summary: 'Response shape changed between snapshots.',
      breaking: false,
      breakingReason: '',
      highlights: [
        { change: 'See full diff for details', impact: 'Local provider does not perform deep analysis.' },
      ],
    };
  }

  _generateSpec() {
    return [
      'openapi: 3.0.3',
      'info:',
      '  title: API',
      '  version: 0.1.0',
      '  description: Generated by local heuristic provider — populate manually.',
      'paths: {}',
    ].join('\n');
  }
}

export default LocalProvider;
