import type { Collection, HistoryEntry } from '../types';

interface DocOptions {
  title: string;
  description: string;
  includeHeaders: boolean;
  includeAuth: boolean;
  includeExamples: boolean;
  format: 'html' | 'markdown';
}

export function generateDocs(collection: Collection, history: HistoryEntry[], options: DocOptions): string {
  return options.format === 'html'
    ? generateHtmlDocs(collection, history, options)
    : generateMarkdownDocs(collection, history, options);
}

function findExampleResponse(url: string, method: string, history: HistoryEntry[]) {
  return history.find(h => h.request.url === url && h.request.method === method && h.response && h.response.status > 0)?.response;
}

function generateMarkdownDocs(col: Collection, history: HistoryEntry[], opts: DocOptions): string {
  let md = `# ${opts.title || col.name}\n\n`;
  if (opts.description) md += `${opts.description}\n\n`;
  md += `> Generated by FetchLab | ${new Date().toLocaleDateString()}\n\n`;
  md += `## Endpoints\n\n`;
  md += `| Method | Endpoint | Description |\n|--------|----------|-------------|\n`;
  col.requests.forEach(r => {
    md += `| \`${r.method}\` | \`${r.url}\` | ${r.name} |\n`;
  });
  md += '\n---\n\n';

  col.requests.forEach((req, i) => {
    md += `## ${i + 1}. ${req.name || req.url}\n\n`;
    md += `\`\`\`\n${req.method} ${req.url}\n\`\`\`\n\n`;

    const params = req.params.filter(p => p.enabled && p.key);
    if (params.length > 0) {
      md += `### Query Parameters\n\n| Parameter | Value |\n|-----------|-------|\n`;
      params.forEach(p => { md += `| \`${p.key}\` | \`${p.value}\` |\n`; });
      md += '\n';
    }

    if (opts.includeHeaders) {
      const headers = req.headers.filter(h => h.enabled && h.key);
      if (headers.length > 0) {
        md += `### Headers\n\n| Header | Value |\n|--------|-------|\n`;
        headers.forEach(h => { md += `| \`${h.key}\` | \`${h.value}\` |\n`; });
        md += '\n';
      }
    }

    if (req.body.type !== 'none' && req.body.content) {
      md += `### Request Body (${req.body.type})\n\n\`\`\`json\n${req.body.content}\n\`\`\`\n\n`;
    }

    if (opts.includeExamples) {
      const example = findExampleResponse(req.url, req.method, history);
      if (example) {
        md += `### Example Response\n\n\`Status: ${example.status} ${example.statusText}\`\n\n`;
        try {
          md += `\`\`\`json\n${JSON.stringify(JSON.parse(example.body), null, 2).substring(0, 2000)}\n\`\`\`\n\n`;
        } catch {
          md += `\`\`\`\n${example.body.substring(0, 1000)}\n\`\`\`\n\n`;
        }
      }
    }
    md += '---\n\n';
  });
  return md;
}

function generateHtmlDocs(col: Collection, history: HistoryEntry[], opts: DocOptions): string {
  const methodColors: Record<string, string> = {
    GET: '#22c55e', POST: '#3b82f6', PUT: '#f59e0b', PATCH: '#a78bfa', DELETE: '#ef4444', HEAD: '#06b6d4', OPTIONS: '#ec4899'
  };

  let endpoints = '';
  col.requests.forEach((req, i) => {
    const color = methodColors[req.method] || '#6b7280';
    const params = req.params.filter(p => p.enabled && p.key);
    const headers = req.headers.filter(h => h.enabled && h.key);
    const example = opts.includeExamples ? findExampleResponse(req.url, req.method, history) : null;

    let bodyHtml = '';
    if (req.body.type !== 'none' && req.body.content) {
      bodyHtml = `<div class="section"><h4>Request Body <span class="badge">${req.body.type}</span></h4><pre>${escapeHtml(req.body.content)}</pre></div>`;
    }

    let paramsHtml = '';
    if (params.length > 0) {
      paramsHtml = `<div class="section"><h4>Query Parameters</h4><table><tr><th>Parameter</th><th>Value</th></tr>${params.map(p => `<tr><td><code>${escapeHtml(p.key)}</code></td><td><code>${escapeHtml(p.value)}</code></td></tr>`).join('')}</table></div>`;
    }

    let headersHtml = '';
    if (opts.includeHeaders && headers.length > 0) {
      headersHtml = `<div class="section"><h4>Headers</h4><table><tr><th>Header</th><th>Value</th></tr>${headers.map(h => `<tr><td><code>${escapeHtml(h.key)}</code></td><td><code>${escapeHtml(h.value)}</code></td></tr>`).join('')}</table></div>`;
    }

    let exampleHtml = '';
    if (example) {
      let exBody = example.body;
      try { exBody = JSON.stringify(JSON.parse(example.body), null, 2); } catch {}
      exampleHtml = `<div class="section"><h4>Example Response <span class="badge" style="background:${example.status < 400 ? '#166534' : '#991b1b'};color:${example.status < 400 ? '#86efac' : '#fca5a5'}">${example.status}</span></h4><pre>${escapeHtml(exBody.substring(0, 3000))}</pre></div>`;
    }

    endpoints += `
      <div class="endpoint" id="endpoint-${i}">
        <div class="endpoint-header">
          <span class="method" style="background:${color}20;color:${color};border:1px solid ${color}40">${req.method}</span>
          <code class="url">${escapeHtml(req.url)}</code>
        </div>
        <p class="endpoint-name">${escapeHtml(req.name)}</p>
        ${paramsHtml}${headersHtml}${bodyHtml}${exampleHtml}
      </div>`;
  });

  let navItems = col.requests.map((r, i) =>
    `<a href="#endpoint-${i}" class="nav-item"><span class="nav-method" style="color:${methodColors[r.method] || '#6b7280'}">${r.method}</span><span class="nav-name">${escapeHtml(r.name || r.url)}</span></a>`
  ).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(opts.title || col.name)} — API Docs</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,sans-serif;background:#0a0a0f;color:#e5e7eb;display:flex;min-height:100vh}
.sidebar{width:260px;background:#111118;border-right:1px solid #1e1e2e;padding:20px 0;position:fixed;top:0;bottom:0;overflow-y:auto}
.sidebar h2{padding:0 20px;font-size:14px;color:#60a5fa;margin-bottom:16px;letter-spacing:0.5px}
.nav-item{display:flex;align-items:center;gap:8px;padding:8px 20px;font-size:13px;color:#9ca3af;text-decoration:none;transition:background .15s}
.nav-item:hover{background:#1e1e2e;color:#f3f4f6}
.nav-method{font-family:monospace;font-size:10px;font-weight:700;width:44px;flex-shrink:0}
.nav-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.main{margin-left:260px;flex:1;padding:40px;max-width:900px}
.main h1{font-size:28px;color:#f9fafb;margin-bottom:8px}
.main .desc{color:#9ca3af;margin-bottom:32px;font-size:15px}
.main .meta{color:#6b7280;font-size:12px;margin-bottom:40px}
.endpoint{background:#111118;border:1px solid #1e1e2e;border-radius:12px;padding:24px;margin-bottom:24px}
.endpoint-header{display:flex;align-items:center;gap:12px;margin-bottom:8px}
.method{font-family:monospace;font-size:12px;font-weight:700;padding:4px 10px;border-radius:6px}
.url{font-size:14px;color:#d1d5db;word-break:break-all}
.endpoint-name{font-size:13px;color:#9ca3af;margin-bottom:16px}
.section{margin-top:16px}
.section h4{font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:8px;display:flex;align-items:center;gap:6px}
.badge{font-size:10px;padding:2px 6px;border-radius:4px;background:#1e293b;color:#94a3b8}
table{width:100%;border-collapse:collapse;font-size:13px}
th{text-align:left;padding:6px 12px;background:#0a0a0f;color:#6b7280;font-weight:500;font-size:11px;text-transform:uppercase}
td{padding:6px 12px;border-top:1px solid #1e1e2e}
pre{background:#0a0a0f;border:1px solid #1e1e2e;border-radius:8px;padding:16px;font-size:12px;font-family:monospace;overflow-x:auto;color:#d1d5db;line-height:1.6;white-space:pre-wrap;word-break:break-all}
code{font-family:monospace;font-size:12px}
@media(max-width:768px){.sidebar{display:none}.main{margin-left:0;padding:20px}}
</style>
</head>
<body>
<nav class="sidebar"><h2>${escapeHtml(opts.title || col.name)}</h2>${navItems}</nav>
<main class="main">
<h1>${escapeHtml(opts.title || col.name)}</h1>
${opts.description ? `<p class="desc">${escapeHtml(opts.description)}</p>` : ''}
<p class="meta">Generated by FetchLab &middot; ${col.requests.length} endpoints &middot; ${new Date().toLocaleDateString()}</p>
${endpoints}
</main>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
